
// GDL APP v3.0
const FIELD_NAMES={1:"Loslassen & aufgeben",2:"Alles unter seine Herrschaft",3:"Vertrauen in Gottes Macht",4:"Aus der Fülle des Vaters"};
const FIELD_COLORS={1:"#8B2020",2:"#2c5f2e",3:"#1a4a7a",4:"#6b3d8a"};
const ACKER_NAMES={1:"Weg (V.4,19)",2:"Felsiger Boden (V.5-6)",3:"Dornen (V.7,22)",4:"Guter Boden (V.8,23)"};
const ZP_STEP_ICONS={step:"📋",resource:"🔧",skill:"📚",person:"👤",prayer:"🙏"};
const ZP_STEP_LABELS={step:"Schritt",resource:"Ressource",skill:"Fähigkeit",person:"Person",prayer:"Gebet"};
const i18n={de:{headerSub:"Seelsorge & Jüngerschafts-Coaching"},en:{headerSub:"Pastoral Care & Discipleship Coaching"},fr:{headerSub:"Accompagnement pastoral & Discipulat"}};

let currentStep=1,selectedField=0,selectedAcker=0,selectedVerseRef="",selectedVerseText="";
let currentImpulseIndex=0,currentLang="de";
let mentees=JSON.parse(localStorage.getItem("gdl_mentees")||"[]");
let journal=JSON.parse(localStorage.getItem("gdl_journal")||"[]");
let savedMentors=JSON.parse(localStorage.getItem("gdl_mentors")||"[]");
let orientData=JSON.parse(localStorage.getItem("gdl_orient")||"{}");
let wirkData=JSON.parse(localStorage.getItem("gdl_wirk")||"{}");
let zpSavedPlans=JSON.parse(localStorage.getItem("gdl_zielplaene")||"[]");
let zpData={mentee:"",goalText:"",goalType:"",goalKind:"",reformulated:"",motivation:"",successCriteria:"",bibleVerse:"",steps:[],lernfelder:[],lernfeldHelp:"",helpers:[],finalDate:"",milestones:[],currentStep:1};
let zpSelectedLernfelder=[],zpCurrentId=null,zpMilestones=[];
let breathRunning=false,breathTimer=null,breathCycleCount=0,phaseIdx=0;
let currentCrisisType=null,deferredInstallPrompt=null;
let crosshairHistory=JSON.parse(localStorage.getItem("gdl_crosshair")||"[]");

function setLang(lang){currentLang=lang;document.querySelectorAll(".lang-btn").forEach(b=>b.classList.remove("active"));const btn=document.querySelector(`.lang-btn[onclick="setLang('${lang}')"]`);if(btn)btn.classList.add("active");const el=document.getElementById("headerSub");if(el)el.textContent=i18n[lang].headerSub;}
function showPage(id){document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));document.querySelectorAll(".nav-tab").forEach(t=>t.classList.remove("active"));const page=document.getElementById("page-"+id);if(page)page.classList.add("active");document.querySelectorAll(".nav-tab").forEach(t=>{if(t.getAttribute("onclick")&&t.getAttribute("onclick").includes("'"+id+"'"))t.classList.add("active");});if(id==="bible")renderBiblePage();if(id==="daily")renderDailyImpulse();if(id==="journal")renderJournal();if(id==="mentoring")renderMentees();if(id==="orientierung")renderOrientierung();if(id==="wirksamkeit")renderWirksamkeit();if(id==="zielplan"){renderZpSavedList();renderZpMenteeSelect();zpGoToStep(zpData.currentStep||1);}if(id==="settings"){updatePWAStatus();updateDataOverview();}window.scrollTo({top:0,behavior:"smooth"});}
function goToStep(n){currentStep=n;document.querySelectorAll(".step-content").forEach(s=>s.classList.remove("active"));const sc=document.getElementById("step-"+n);if(sc)sc.classList.add("active");document.querySelectorAll(".step-item").forEach((s,i)=>{s.classList.remove("active","done");if(i+1<n)s.classList.add("done");if(i+1===n)s.classList.add("active");});if(n===4)renderBibleResults(BIBLE_LIBRARY);}
function setSessionField(f){selectedField=f;showPage("session");goToStep(2);selectField(f);}
function selectField(f){selectedField=f;[1,2,3,4].forEach(i=>{const el=document.getElementById("fc"+i);if(el)el.classList.toggle("selected",i===f);});}
function selectAcker(n){selectedAcker=n;[1,2,3,4].forEach(i=>{const el=document.getElementById("ac"+i);if(el)el.classList.toggle("selected",i===n);});}
function highlightField(f){showPage("session");setSessionField(f);}
function searchBible(){const q=document.getElementById("bibleSearchInput").value.toLowerCase();renderBibleResults(q.length<2?BIBLE_LIBRARY:BIBLE_LIBRARY.filter(v=>v.ref.toLowerCase().includes(q)||v.text.toLowerCase().includes(q)||v.tags.some(t=>t.includes(q))));}
function filterBibleByField(f){renderBibleResults(f===0?BIBLE_LIBRARY:BIBLE_LIBRARY.filter(v=>v.field===f));}
function renderBibleResults(verses){const c=document.getElementById("bibleResults");if(!c)return;if(!verses.length){c.innerHTML='<div class="alert alert-warning"><span>🔍</span><span>Keine Verse gefunden.</span></div>';return;}c.innerHTML=verses.map(v=>`<div class="bv-item" onclick="selectVerse(${JSON.stringify(v.ref)},${JSON.stringify(v.text)})"><div class="ref">${v.ref}</div><div class="txt">${v.text.substring(0,110)}${v.text.length>110?"...":""}</div><span class="ftag tag-f${v.field}">${FIELD_NAMES[v.field]}</span></div>`).join("");}
function selectVerse(ref,text){selectedVerseRef=ref;selectedVerseText=text;const box=document.getElementById("selectedVerseBox");if(box){box.classList.remove("hidden");document.getElementById("selectedVerseRef").textContent=ref;document.getElementById("selectedVerseText").textContent=text;}}
function renderBiblePage(){filterBiblePage(0);}
function searchBiblePage(){const q=document.getElementById("biblePageSearch").value.toLowerCase();renderBiblePageResults(q.length<2?BIBLE_LIBRARY:BIBLE_LIBRARY.filter(v=>v.ref.toLowerCase().includes(q)||v.text.toLowerCase().includes(q)||v.tags.some(t=>t.includes(q))));}
function filterBiblePage(f){renderBiblePageResults(f===0?BIBLE_LIBRARY:BIBLE_LIBRARY.filter(v=>v.field===f));}
function renderBiblePageResults(verses){const c=document.getElementById("biblePageResults");if(!c)return;c.innerHTML=verses.map(v=>`<div class="bv-item"><div class="ref">${v.ref}</div><div class="txt">${v.text}</div><span class="ftag tag-f${v.field}">${FIELD_NAMES[v.field]}</span></div>`).join("");}
function renderDailyImpulse(){const today=new Date();currentImpulseIndex=Math.floor((today-new Date(today.getFullYear(),0,0))/86400000)%DAILY_IMPULSES.length;showImpulse(currentImpulseIndex);}
function loadNextImpulse(){currentImpulseIndex=(currentImpulseIndex+1)%DAILY_IMPULSES.length;showImpulse(currentImpulseIndex);}
function showImpulse(idx){const imp=DAILY_IMPULSES[idx],today=new Date();const dd=document.getElementById("dailyDate");if(dd)dd.textContent=today.toLocaleDateString("de-DE",{weekday:"long",year:"numeric",month:"long",day:"numeric"});const dr=document.getElementById("dailyRef");if(dr)dr.textContent=imp.ref;const dv=document.getElementById("dailyVerse");if(dv)dv.textContent="\u201e"+imp.verse+"\u201c";const df=document.getElementById("dailyField");if(df){df.textContent=FIELD_NAMES[imp.field];df.style.background=FIELD_COLORS[imp.field];}const dref=document.getElementById("dailyReflections");if(dref)dref.innerHTML=imp.reflections.map(r=>`<div class="refl-q"><p>🤔 ${r}</p><textarea placeholder="Meine Gedanken..."></textarea></div>`).join("");const dp=document.getElementById("dailyPrayer");if(dp)dp.innerHTML=`<span>🙏</span><span>${imp.prayer}</span>`;}
function saveSession(){const g=id=>document.getElementById(id)?document.getElementById(id).value:"";const situation=g("situationText");const goal=g("goalText");if(!situation&&!goal)return;const entry={id:Date.now(),date:new Date().toLocaleDateString("de-DE"),sessionDate:g("sessionDate"),menteeName:g("menteePdfName"),field:selectedField,situation,context:g("contextSelect"),sitFeelings:g("sit_feelings"),sitThoughts:g("sit_thoughts"),sitGod:g("sit_god"),sitBurden:g("sit_burden")||"5",acker:selectedAcker,ackerReflection:g("ackerReflection"),actionType:g("actionType"),bibleRef:selectedVerseRef,bibleText:selectedVerseText,bibleThoughts:g("bibleThoughts"),ownThoughts:g("ownThoughts"),selfInsight:g("selfInsight"),prayerThought:g("prayerThought"),goal,timeframe:g("goalTimeframe"),accountability:g("accountability"),nextMeeting:g("nextMeeting"),closingPrayer:g("closingPrayer")};journal.unshift(entry);localStorage.setItem("gdl_journal",JSON.stringify(journal));const ss=document.getElementById("sessionSaved");if(ss){ss.classList.remove("hidden");setTimeout(()=>ss.classList.add("hidden"),3000);}showToast("✅ Gespräch gespeichert!");}
function renderJournal(){const c=document.getElementById("journalEntries");if(!c)return;if(!journal.length){c.innerHTML='<div class="alert alert-info"><span>📝</span><span>Noch keine Einträge. Starte ein Gespräch und speichere es.</span></div>';return;}c.innerHTML=journal.map(e=>`<div class="je"><div class="je-date">📅 ${e.date}${e.menteeName?" · "+e.menteeName:""}</div>${e.field?`<span class="je-field" style="background:${FIELD_COLORS[e.field]}">${FIELD_NAMES[e.field]}</span>`:""}<div class="je-title">${e.situation?e.situation.substring(0,80)+(e.situation.length>80?"...":""):"Gespräch"}</div>${e.bibleRef?`<div style="font-size:.79rem;color:var(--primary-dark);margin:3px 0;">📖 ${e.bibleRef}</div>`:""} ${e.goal?`<div class="je-goal">🎯 ${e.goal.substring(0,80)}</div>`:""}<div class="je-actions"><button class="btn btn-secondary btn-sm" onclick="exportEntryPDF(${e.id})">📄 Protokoll</button><button class="btn btn-danger btn-sm" onclick="deleteEntry(${e.id})">🗑</button></div></div>`).join("");}
function deleteEntry(id){journal=journal.filter(e=>e.id!==id);localStorage.setItem("gdl_journal",JSON.stringify(journal));renderJournal();}
function clearJournal(){if(confirm("Wirklich alle Einträge löschen?")){journal=[];localStorage.setItem("gdl_journal",JSON.stringify(journal));renderJournal();}}




function renderOrientierung(){const sections=[{key:"wichtig",id:"orient_wichtig"},{key:"lebe",id:"orient_lebe"},{key:"unwichtig",id:"orient_unwichtig"},{key:"hilfe",id:"orient_hilfe"}];sections.forEach(({key,id})=>{const c=document.getElementById(id);if(!c)return;c.innerHTML=ORIENT_QUESTIONS[key].map((q,i)=>{const saved=orientData[key]&&orientData[key][i];return `<div class="orient-q ${saved?"selected-"+saved:""}" id="oq_${key}_${i}"><div class="orient-q-text">${q}</div><div class="orient-q-btns"><button class="orient-btn orient-btn-yes ${saved==="yes"?"active":""}" onclick="setOrientAnswer('${key}',${i},'yes')">✅</button><button class="orient-btn orient-btn-no ${saved==="no"?"active":""}" onclick="setOrientAnswer('${key}',${i},'no')">❌</button><button class="orient-btn orient-btn-help ${saved==="help"?"active":""}" onclick="setOrientAnswer('${key}',${i},'help')">🆘</button></div></div>`;}).join("");});updateOrientOverview();}
function setOrientAnswer(key,idx,val){if(!orientData[key])orientData[key]={};orientData[key][idx]=val;const el=document.getElementById(`oq_${key}_${idx}`);if(el){el.className=`orient-q selected-${val}`;el.querySelectorAll(".orient-btn").forEach(b=>b.classList.remove("active"));const btn=el.querySelector(`.orient-btn-${val}`);if(btn)btn.classList.add("active");}updateOrientOverview();}
function updateOrientOverview(){const c=document.getElementById("orient_overview");if(!c)return;const counts={yes:0,no:0,help:0};Object.values(orientData).forEach(section=>{Object.values(section).forEach(v=>{counts[v]=(counts[v]||0)+1;});});c.innerHTML=`<div style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px;"><div style="text-align:center;padding:10px;background:#e8f8e8;border-radius:8px;"><div style="font-size:1.4rem;">✅</div><div style="font-weight:700;font-size:1.1rem;color:#155724;">${counts.yes||0}</div><div style="font-size:.75rem;color:#666;">Ja / Lebe ich</div></div><div style="text-align:center;padding:10px;background:#fdf0f0;border-radius:8px;"><div style="font-size:1.4rem;">❌</div><div style="font-weight:700;font-size:1.1rem;color:#721c24;">${counts.no||0}</div><div style="font-size:.75rem;color:#666;">Nein / Noch nicht</div></div><div style="text-align:center;padding:10px;background:#e8f4fd;border-radius:8px;"><div style="font-size:1.4rem;">🆘</div><div style="font-weight:700;font-size:1.1rem;color:#0c5460;">${counts.help||0}</div><div style="font-size:.75rem;color:#666;">Brauche Hilfe</div></div></div>`;}
function saveOrientierung(){localStorage.setItem("gdl_orient",JSON.stringify(orientData));showToast("✅ Orientierung gespeichert!");}
function renderWirksamkeit(){const sections=[{key:"f1",id:"wirk_f1",color:"#8B2020"},{key:"f2",id:"wirk_f2",color:"#2c5f2e"},{key:"f3",id:"wirk_f3",color:"#1a4a7a"},{key:"f4",id:"wirk_f4",color:"#6b3d8a"},{key:"fruechte",id:"wirk_fruechte",color:"#27ae60"}];sections.forEach(({key,id,color})=>{const c=document.getElementById(id);if(!c)return;c.innerHTML=WIRK_ITEMS[key].map((item,i)=>{const val=wirkData[key]&&wirkData[key][i]!==undefined?wirkData[key][i]:5;return `<div class="wirk-item"><div class="wirk-item-label">${item.label}</div><input type="range" min="1" max="10" value="${val}" class="wirk-slider" style="width:100px;" oninput="updateWirkItem('${key}',${i},this.value)"><div class="wirk-val" id="wv_${key}_${i}" style="color:${color};">${val}</div></div>`;}).join("");});updateWirkOverview();updateCrosshair();}
function updateWirkItem(key,idx,val){if(!wirkData[key])wirkData[key]={};wirkData[key][idx]=parseInt(val);const el=document.getElementById(`wv_${key}_${idx}`);if(el)el.textContent=val;updateWirkOverview();}
function updateWirkOverview(){const c=document.getElementById("wirk_overview");if(!c)return;const keys=["f1","f2","f3","f4","fruechte"];const colors=["#8B2020","#2c5f2e","#1a4a7a","#6b3d8a","#27ae60"];const labels=["Loslassen & aufgeben","Alles unter seine Herrschaft","Vertrauen in Gottes Macht","Aus der Fülle des Vaters","Früchte des Geistes"];c.innerHTML=keys.map((key,ki)=>{const items=WIRK_ITEMS[key];const vals=items.map((_,i)=>wirkData[key]&&wirkData[key][i]!==undefined?wirkData[key][i]:5);const avg=Math.round(vals.reduce((a,b)=>a+b,0)/vals.length);const pct=(avg/10)*100;return `<div class="zp-progress-item"><div class="zp-progress-label"><span style="font-size:.8rem;color:${colors[ki]};">${labels[ki]}</span><span style="font-weight:700;color:${colors[ki]};">${avg}/10</span></div><div class="zp-progress-bar"><div class="zp-progress-fill" style="width:${pct}%;background:${colors[ki]};"></div></div></div>`;}).join("");}
function saveWirksamkeit(){localStorage.setItem("gdl_wirk",JSON.stringify(wirkData));const point=getCrosshairPoint();crosshairHistory.push({...point,date:new Date().toLocaleDateString("de-DE"),ts:Date.now()});if(crosshairHistory.length>10)crosshairHistory.shift();localStorage.setItem("gdl_crosshair",JSON.stringify(crosshairHistory));updateCrosshair();showToast("✅ Wirksamkeitsanalyse gespeichert!");}
function getCrosshairPoint(){const avg=key=>{const items=WIRK_ITEMS[key];const vals=items.map((_,i)=>wirkData[key]&&wirkData[key][i]!==undefined?wirkData[key][i]:5);return vals.reduce((a,b)=>a+b,0)/vals.length;};return{f1:avg("f1"),f2:avg("f2"),f3:avg("f3"),f4:avg("f4"),fruechte:avg("fruechte")};}
function updateCrosshair(){const svg=document.getElementById("crosshairSVG");if(!svg)return;const pts=document.getElementById("crosshairPoints");if(!pts)return;pts.innerHTML="";const pt=getCrosshairPoint();const toX=v=>200+(v-5)*36;const toY=v=>200-(v-5)*36;const cx=toX((pt.f2+pt.f4)/2);const cy=toY((pt.f1+pt.f3)/2);crosshairHistory.slice(-5).forEach((h,i)=>{const hx=toX((h.f2+h.f4)/2);const hy=toY((h.f1+h.f3)/2);const opacity=0.25+(i/5)*0.5;pts.innerHTML+=`<circle cx="${hx}" cy="${hy}" r="5" fill="#c8a84b" opacity="${opacity}" stroke="white" stroke-width="1"/>`;if(i>0){const prev=crosshairHistory[crosshairHistory.length-5+i-1];if(prev){const px=toX((prev.f2+prev.f4)/2);const py=toY((prev.f1+prev.f3)/2);pts.innerHTML+=`<line x1="${px}" y1="${py}" x2="${hx}" y2="${hy}" stroke="#c8a84b" stroke-width="1" opacity="${opacity}" stroke-dasharray="3,2"/>`;}}});pts.innerHTML+=`<circle cx="${cx}" cy="${cy}" r="11" fill="#3498db" opacity=".88" stroke="white" stroke-width="2.5"/><text x="${cx}" y="${cy+4}" text-anchor="middle" fill="white" font-size="8" font-weight="bold" font-family="Segoe UI,sans-serif">Jetzt</text>`;pts.innerHTML+=`<circle cx="${toX(9)}" cy="${toY(9)}" r="8" fill="#27ae60" opacity=".75" stroke="white" stroke-width="1.5"/><text x="${toX(9)}" y="${toY(9)+4}" text-anchor="middle" fill="white" font-size="7" font-family="Segoe UI,sans-serif">Ziel</text>`;}
function openCrisisModal(){resetCrisisModal();document.getElementById("crisisModal").classList.add("open");stopBreath();}
function closeCrisisModal(){document.getElementById("crisisModal").classList.remove("open");stopBreath();}
function resetCrisisModal(){currentCrisisType=null;document.getElementById("crisisTypeSelector").classList.remove("hidden");document.getElementById("crisisContent").classList.add("hidden");document.getElementById("crisisBackBtn").style.display="none";document.querySelectorAll(".crisis-type-card").forEach(c=>c.classList.remove("selected"));showCrisisTab("steps");stopBreath();}
function selectCrisisType(type,el){currentCrisisType=type;document.querySelectorAll(".crisis-type-card").forEach(c=>c.classList.remove("selected"));if(el)el.classList.add("selected");document.getElementById("crisisTypeSelector").classList.add("hidden");document.getElementById("crisisContent").classList.remove("hidden");document.getElementById("crisisBackBtn").style.display="inline-flex";renderCrisisSteps(type);renderCrisisPrayers(type);renderSavedMentors();}
function renderCrisisSteps(type){const ct=CRISIS_TYPES[type];document.getElementById("crisisStepsContent").innerHTML=`<div class="alert alert-danger" style="margin-bottom:10px;"><span>${ct.label}</span></div>`+ct.steps.map((s,i)=>`<div class="crisis-step"><div class="cs-num">${i+1}</div><div class="cs-text"><strong>${s.t}</strong><p>${s.d}</p></div></div>`).join("");}
function renderCrisisPrayers(type){const ct=CRISIS_TYPES[type];document.getElementById("crisisPrayerContent").innerHTML=ct.prayers.map(pid=>{const p=CRISIS_PRAYERS[pid];return `<div class="prayer-card" onclick="togglePrayer('${pid}')"><h4>🙏 ${p.title}</h4><div class="prayer-short">${p.short}</div><div class="prayer-full" id="pf-${pid}"><p>${p.full}</p><div class="prayer-verse">📖 ${p.verse}</div></div></div>`;}).join("");}
function togglePrayer(pid){const el=document.getElementById("pf-"+pid);if(el)el.classList.toggle("open");}
function showCrisisTab(tab){document.querySelectorAll(".crisis-tab").forEach((t,i)=>{const tabs=["steps","breath","prayer","contacts"];t.classList.toggle("active",tabs[i]===tab);});document.querySelectorAll(".crisis-panel").forEach(p=>p.classList.remove("active"));const panel=document.getElementById("crisis-"+tab);if(panel)panel.classList.add("active");if(tab==="breath")resetBreath();}
const PHASES=[{name:"inhale",label:"Einatmen",dur:4,cls:"inhale"},{name:"hold",label:"Halten",dur:7,cls:"hold"},{name:"exhale",label:"Ausatmen",dur:8,cls:"exhale"}];
function toggleBreath(){if(breathRunning)stopBreath();else startBreath();}
function startBreath(){breathRunning=true;phaseIdx=0;breathCycleCount=0;const btn=document.getElementById("breathBtn");if(btn)btn.textContent="⏸ Pause";runBreathPhase();}
function runBreathPhase(){if(!breathRunning)return;const ph=PHASES[phaseIdx];const circle=document.getElementById("breathCircle");const fill=document.getElementById("breathFill");if(circle)circle.className="breath-circle "+ph.cls;const instr=document.getElementById("breathInstruction");if(instr)instr.textContent=ph.label;let sec=ph.dur;const cnt=document.getElementById("breathCount");if(cnt)cnt.textContent=sec;if(fill){fill.style.width="0%";setTimeout(()=>{fill.style.transition=`width ${ph.dur}s linear`;fill.style.width="100%";},50);}breathTimer=setInterval(()=>{sec--;if(cnt)cnt.textContent=sec;if(sec<=0){clearInterval(breathTimer);phaseIdx=(phaseIdx+1)%3;if(phaseIdx===0){breathCycleCount++;const cyc=document.getElementById("breathCycles");if(cyc)cyc.textContent=`Zyklen: ${breathCycleCount} / 4`;if(breathCycleCount>=4){stopBreath();if(instr)instr.textContent="Fertig!";if(cnt)cnt.textContent="✓";return;}}if(fill){fill.style.transition="none";fill.style.width="0%";}setTimeout(runBreathPhase,300);}},1000);}
function stopBreath(){breathRunning=false;clearInterval(breathTimer);const btn=document.getElementById("breathBtn");if(btn)btn.textContent="▶ Start";}
function resetBreath(){stopBreath();breathCycleCount=0;phaseIdx=0;const circle=document.getElementById("breathCircle");if(circle){circle.className="breath-circle";circle.textContent="Bereit";}const instr=document.getElementById("breathInstruction");if(instr)instr.textContent="Drücke Start";const cnt=document.getElementById("breathCount");if(cnt)cnt.textContent="–";const fill=document.getElementById("breathFill");if(fill){fill.style.transition="none";fill.style.width="0%";}const cyc=document.getElementById("breathCycles");if(cyc)cyc.textContent="Zyklen: 0 / 4";}
function saveMentor(){const name=document.getElementById("mentorName").value.trim();const phone=document.getElementById("mentorPhone").value.trim();if(!name)return;savedMentors.push({id:Date.now(),name,phone});localStorage.setItem("gdl_mentors",JSON.stringify(savedMentors));document.getElementById("mentorName").value="";document.getElementById("mentorPhone").value="";renderSavedMentors();}
function renderSavedMentors(){const c=document.getElementById("savedMentors");if(!c)return;if(!savedMentors.length){c.innerHTML='<p style="font-size:.8rem;color:var(--text-light);">Noch keine Mentoren gespeichert.</p>';return;}c.innerHTML=savedMentors.map(m=>`<div class="saved-mentor"><strong>${m.name}</strong><span>${m.phone||""}</span>${m.phone?`<a href="tel:${m.phone}" class="btn btn-primary btn-sm">📞</a>`:""}<button class="btn btn-danger btn-sm" onclick="deleteMentor(${m.id})">🗑</button></div>`).join("");}
function deleteMentor(id){savedMentors=savedMentors.filter(m=>m.id!==id);localStorage.setItem("gdl_mentors",JSON.stringify(savedMentors));renderSavedMentors();}
const ZP_KIND_HINTS={spiritual:"✝ Geistliches Ziel: Plane Gebetszeiten und Bibelstellen als feste Schritte ein.",practical:"🔧 Praktisches Ziel: Wie ehre ich Gott auf dem Weg zu diesem Ziel?",both:"✝🔧 Geistlich-praktisches Ziel: Das ist oft das Kraftvollste!"};
function selectZpKind(kind){zpData.goalKind=kind;["spiritual","practical","both"].forEach(k=>{const el=document.getElementById("zp_kind_"+k);if(!el)return;el.style.borderColor=k===kind?"var(--primary)":"#d4c9b0";el.style.background=k===kind?"#e8f0e8":"";});const hint=document.getElementById("zp_kind_hint");if(hint){hint.textContent=ZP_KIND_HINTS[kind];hint.classList.remove("hidden");}}
function selectGoalType(type){zpData.goalType=type;const g=document.getElementById("zp_type_goal");const w=document.getElementById("zp_type_wish");const hint=document.getElementById("zp_wish_hint");if(type==="goal"){if(g)g.style.borderColor="#2c5f2e";if(w)w.style.borderColor="#d4c9b0";if(hint)hint.classList.add("hidden");}else{if(w)w.style.borderColor="#c8a84b";if(g)g.style.borderColor="#d4c9b0";if(hint)hint.classList.remove("hidden");}}
function checkSmartResult(){const checks=["smart_s","smart_m","smart_a","smart_r","smart_t"].map(id=>{const el=document.getElementById(id);return el?el.checked:false;});const count=checks.filter(Boolean).length;const res=document.getElementById("smart_result");if(!res)return;res.style.display="block";if(count===5){res.style.background="#e8f8e8";res.style.color="#1a5c2a";res.textContent="✅ Ausgezeichnet! Dein Ziel erfüllt alle SMART-Kriterien!";}else if(count>=3){res.style.background="#fef9e7";res.style.color="#7d6608";res.textContent=`⚠️ ${count}/5 Kriterien erfüllt.`;}else{res.style.background="#fdf0f0";res.style.color="#7b241c";res.textContent=`❌ Nur ${count}/5 Kriterien. Das klingt eher nach einem Wunsch.`;}}
function toggleZpLernfeld(f){const el=document.getElementById("zp_lf"+f);const idx=zpSelectedLernfelder.indexOf(f);if(idx>=0){zpSelectedLernfelder.splice(idx,1);if(el){el.style.opacity=".7";el.style.transform="";}}else{zpSelectedLernfelder.push(f);if(el){el.style.opacity="1";el.style.transform="scale(1.03)";}}}
function addZpStep(){const text=document.getElementById("zp_new_step").value.trim();const type=document.getElementById("zp_step_type").value;if(!text)return;zpData.steps.push({id:Date.now(),text,type,deadline:"",done:false});document.getElementById("zp_new_step").value="";renderZpStepsList();updateZpTimelineSelect();}
function renderZpStepsList(){const c=document.getElementById("zp_steps_list");if(!c)return;if(!zpData.steps.length){c.innerHTML='<p style="font-size:.8rem;color:var(--text-light);font-style:italic;">Noch keine Schritte.</p>';return;}c.innerHTML=zpData.steps.map((s,i)=>`<div class="zp-step-item ${s.done?"done":""}"><div class="zp-step-num">${i+1}</div><div style="font-size:.9rem;margin-right:4px;">${ZP_STEP_ICONS[s.type]||"📋"}</div><div class="zp-step-text"><div>${s.text}</div><div class="zp-step-date">${s.deadline?"📅 "+formatDate(s.deadline):""}</div></div><div style="display:flex;gap:4px;"><button class="btn btn-sm" style="background:#e8f8e8;color:#2c5f2e;padding:3px 7px;" onclick="moveZpStep(${i},-1)">↑</button><button class="btn btn-sm" style="background:#e8f8e8;color:#2c5f2e;padding:3px 7px;" onclick="moveZpStep(${i},1)">↓</button><button class="btn btn-danger btn-sm" style="padding:3px 7px;" onclick="removeZpStep(${i})">✕</button></div></div>`).join("");}
function moveZpStep(idx,dir){const ni=idx+dir;if(ni<0||ni>=zpData.steps.length)return;[zpData.steps[idx],zpData.steps[ni]]=[zpData.steps[ni],zpData.steps[idx]];renderZpStepsList();updateZpTimelineSelect();}
function removeZpStep(idx){zpData.steps.splice(idx,1);renderZpStepsList();updateZpTimelineSelect();}
function addZpHelper(){const name=document.getElementById("zp_helper_name").value.trim();const what=document.getElementById("zp_helper_what").value.trim();if(!name)return;zpData.helpers.push({name,what});document.getElementById("zp_helper_name").value="";document.getElementById("zp_helper_what").value="";renderZpHelpers();}
function renderZpHelpers(){const c=document.getElementById("zp_helpers_list");if(!c)return;if(!zpData.helpers.length){c.innerHTML="";return;}c.innerHTML=zpData.helpers.map((h,i)=>`<div class="zp-helper-item"><div class="zp-helper-av">${h.name.charAt(0).toUpperCase()}</div><div style="flex:1;"><strong style="font-size:.84rem;">${h.name}</strong><div style="font-size:.76rem;color:var(--text-light);">${h.what}</div></div><button class="btn btn-danger btn-sm" style="padding:3px 7px;" onclick="removeZpHelper(${i})">✕</button></div>`).join("");}
function removeZpHelper(idx){zpData.helpers.splice(idx,1);renderZpHelpers();}
function updateZpTimelineSelect(){const sel=document.getElementById("zp_timeline_step_select");if(!sel)return;sel.innerHTML=zpData.steps.map((s,i)=>`<option value="${i}">${i+1}. ${s.text.substring(0,50)}</option>`).join("");}
function setStepDeadline(){const idx=parseInt(document.getElementById("zp_timeline_step_select").value);const date=document.getElementById("zp_timeline_date").value;if(isNaN(idx)||!date)return;zpData.steps[idx].deadline=date;renderZpTimeline();renderZpStepsList();}
function formatDate(dateStr){if(!dateStr)return"";try{const d=new Date(dateStr+"T00:00:00");return d.toLocaleDateString("de-DE",{day:"2-digit",month:"2-digit",year:"numeric"});}catch(e){return dateStr;}}
function renderZpTimeline(){const c=document.getElementById("zp_timeline");if(!c)return;updateZpTimelineSelect();const today=new Date().toISOString().split("T")[0];const sorted=[...zpData.steps].sort((a,b)=>{if(!a.deadline&&!b.deadline)return 0;if(!a.deadline)return 1;if(!b.deadline)return-1;return a.deadline.localeCompare(b.deadline);});if(!sorted.length){c.innerHTML='<p style="font-size:.8rem;color:var(--text-light);text-align:center;padding:16px;">Noch keine Schritte vorhanden.</p>';return;}const finalDate=document.getElementById("zp_final_date")?document.getElementById("zp_final_date").value:"";let html='<div class="zp-timeline-wrap"><div class="zp-timeline-line"></div>';html+=`<div class="zp-timeline-item"><div class="zp-timeline-dot" style="background:var(--primary);"></div><div class="zp-tl-content" style="border-left:3px solid var(--primary);"><h4>🚀 Startpunkt – Heute</h4><div class="zp-tl-date">${formatDate(today)}</div><span class="zp-tl-type">Ist-Zustand</span></div></div>`;sorted.forEach(s=>{const isOverdue=s.deadline&&s.deadline<today&&!s.done;const color=s.done?"#27ae60":isOverdue?"#c0392b":"#c8a84b";const stepNum=zpData.steps.indexOf(s)+1;html+=`<div class="zp-timeline-item"><div class="zp-timeline-dot" style="background:${color};"></div><div class="zp-tl-content" style="border-left:3px solid ${color};"><h4>${s.done?"✅ ":""}${stepNum}. ${s.text}</h4><div class="zp-tl-date">${s.deadline?"📅 "+formatDate(s.deadline):"⏳ Noch kein Datum"}</div><span class="zp-tl-type">${ZP_STEP_ICONS[s.type]} ${ZP_STEP_LABELS[s.type]}</span>${isOverdue?'<div style="font-size:.7rem;color:#c0392b;margin-top:3px;">⚠️ Termin überschritten</div>':""}</div></div>`;});if(finalDate||zpData.goalText){html+=`<div class="zp-timeline-item"><div class="zp-timeline-dot" style="background:var(--accent);width:20px;height:20px;left:-30px;"></div><div class="zp-tl-content" style="border-left:3px solid var(--accent);background:linear-gradient(135deg,#fef9e7,#fdf0d0);"><h4>🎯 ZIEL ERREICHT!</h4>${zpData.goalText?`<div style="font-size:.8rem;color:#7d6608;margin-top:3px;">${zpData.goalText.substring(0,70)}</div>`:""}<div class="zp-tl-date">${finalDate?"📅 "+formatDate(finalDate):""}</div></div></div>`;}html+="</div>";c.innerHTML=html;}
function addSpiritualMilestone(){const text=document.getElementById("zp_milestone_text").value.trim();const date=document.getElementById("zp_milestone_date").value;if(!text)return;zpMilestones.push({text,date,id:Date.now()});document.getElementById("zp_milestone_text").value="";document.getElementById("zp_milestone_date").value="";renderSpiritualMilestones();}
function renderSpiritualMilestones(){const c=document.getElementById("zp_spiritual_milestones");if(!c)return;if(!zpMilestones.length){c.innerHTML="";return;}c.innerHTML=zpMilestones.map((m,i)=>`<div style="display:flex;align-items:center;gap:7px;padding:5px 9px;background:#e8f4fd;border-radius:6px;margin-bottom:5px;"><span style="font-size:.82rem;flex:1;">✝ ${m.text}${m.date?" – "+formatDate(m.date):""}</span><button class="btn btn-danger btn-sm" style="padding:2px 7px;" onclick="zpMilestones.splice(${i},1);renderSpiritualMilestones()">✕</button></div>`).join("");}
function addCalendarReminder(){const stepIdx=parseInt(document.getElementById("zp_timeline_step_select").value);const step=zpData.steps[stepIdx];const status=document.getElementById("zp_reminder_status");if(!step||!step.deadline){if(status)status.textContent="⚠️ Bitte zuerst ein Datum setzen.";return;}const reminderDays=parseInt(document.getElementById("zp_reminder_days").value);const deadlineDate=new Date(step.deadline+"T09:00:00");const fmt=d=>d.toISOString().replace(/[-:]/g,"").split(".")[0]+"Z";const ics=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//GDL App//DE","BEGIN:VEVENT","UID:"+Date.now()+"@gdl-app","DTSTAMP:"+fmt(new Date()),"DTSTART:"+fmt(deadlineDate),"DTEND:"+fmt(new Date(deadlineDate.getTime()+3600000)),"SUMMARY:GDL Ziel: "+step.text.substring(0,50),"DESCRIPTION:Geistlich Denken Lernen","BEGIN:VALARM","TRIGGER:-P"+reminderDays+"D","ACTION:DISPLAY","DESCRIPTION:Erinnerung: "+step.text.substring(0,40),"END:VALARM","END:VEVENT","END:VCALENDAR"].join("\r\n");const blob=new Blob([ics],{type:"text/calendar"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="GDL-Erinnerung.ics";a.click();URL.revokeObjectURL(url);if(status)status.textContent="✅ Kalender-Datei heruntergeladen!";}
function requestBrowserNotification(){const status=document.getElementById("zp_reminder_status");if(!("Notification"in window)){if(status)status.textContent="⚠️ Browser unterstützt keine Benachrichtigungen.";return;}if(Notification.permission==="granted"){scheduleNotification();}else if(Notification.permission!=="denied"){Notification.requestPermission().then(p=>{if(p==="granted")scheduleNotification();else if(status)status.textContent="⚠️ Benachrichtigungen abgelehnt.";});}else{if(status)status.textContent="⚠️ Benachrichtigungen blockiert.";}}
function scheduleNotification(){const stepIdx=parseInt(document.getElementById("zp_timeline_step_select").value);const step=zpData.steps[stepIdx];const status=document.getElementById("zp_reminder_status");if(!step){if(status)status.textContent="⚠️ Kein Schritt ausgewählt.";return;}new Notification("GDL App – Erinnerung",{body:"Zielschritt: "+step.text.substring(0,60)});if(status)status.textContent="✅ Test-Benachrichtigung gesendet!";}
function zpGoToStep(n){zpData.currentStep=n;[1,2,3,4,5].forEach(i=>{const c=document.getElementById("zp_step"+i+"_card");if(c)c.style.display=i===n?"block":"none";});if(n===4)renderZpTimeline();if(n===5){renderZpProgress();renderZpProgressSVG();renderZpStepChecks();}}
function renderZpProgress(){const c=document.getElementById("zp_progress_overview");if(!c)return;const total=zpData.steps.length;const done=zpData.steps.filter(s=>s.done).length;const pct=total>0?Math.round((done/total)*100):0;const name=document.getElementById("zp_mentee")?document.getElementById("zp_mentee").value||"Mentee":"Mentee";const el=document.getElementById("zp_grafik_name");if(el)el.textContent=name;c.innerHTML=`<div style="background:linear-gradient(135deg,#1a3d1c,#2c5f2e);color:#fff;border-radius:10px;padding:14px;margin-bottom:10px;"><div style="font-size:.82rem;opacity:.8;margin-bottom:3px;">Gesamtfortschritt für ${name}</div><div style="font-size:1.8rem;font-weight:700;">${pct}%</div><div style="background:rgba(255,255,255,.2);border-radius:4px;height:9px;margin-top:7px;overflow:hidden;"><div style="width:${pct}%;height:100%;background:var(--accent);border-radius:4px;transition:width .5s;"></div></div><div style="font-size:.76rem;opacity:.8;margin-top:5px;">${done} von ${total} Schritten abgeschlossen</div></div>`+zpData.steps.map((s,i)=>{const color=s.done?"#27ae60":"#c8a84b";return `<div class="zp-progress-item"><div class="zp-progress-label"><span style="font-size:.78rem;">${i+1}. ${s.text.substring(0,45)}${s.text.length>45?"...":""}</span><span style="font-size:.75rem;color:${color};font-weight:700;">${s.done?"✅ Erledigt":"⏳ Offen"}</span></div><div class="zp-progress-bar"><div class="zp-progress-fill" style="width:${s.done?100:0}%;background:${color};"></div></div></div>`;}).join("");}
function renderZpProgressSVG(){const svg=document.getElementById("zp_progress_svg");if(!svg)return;const total=zpData.steps.length;const done=zpData.steps.filter(s=>s.done).length;const pct=total>0?done/total:0;const name=document.getElementById("zp_mentee")?document.getElementById("zp_mentee").value||"Mentee":"Mentee";const today=new Date().toLocaleDateString("de-DE");const fieldColors=["#8B2020","#2c5f2e","#1a4a7a","#6b3d8a"];const fieldNames=["Loslassen & aufgeben","Alles unter seine Herrschaft","Vertrauen in Gottes Macht","Gegenwart des Vaters"];let svgContent=`<rect width="500" height="320" fill="#f5f0e8" rx="12"/><rect width="500" height="52" fill="#1a3d1c" rx="12"/><rect y="40" width="500" height="12" fill="#1a3d1c"/><text x="20" y="22" fill="white" font-size="13" font-weight="bold" font-family="Segoe UI,sans-serif">✝ Ist-Zustand: ${name.substring(0,25)}</text><text x="20" y="40" fill="rgba(255,255,255,0.7)" font-size="9" font-family="Segoe UI,sans-serif">${today} · Ps 73,28</text><circle cx="70" cy="120" r="45" fill="white" stroke="#e0d8c8" stroke-width="2"/><circle cx="70" cy="120" r="38" fill="none" stroke="#e0d8c8" stroke-width="8"/><circle cx="70" cy="120" r="38" fill="none" stroke="#2c5f2e" stroke-width="8" stroke-dasharray="${Math.round(pct*239)} 239" stroke-dashoffset="60" stroke-linecap="round"/><text x="70" y="115" text-anchor="middle" fill="#1a3d1c" font-size="16" font-weight="bold" font-family="Segoe UI,sans-serif">${Math.round(pct*100)}%</text><text x="70" y="130" text-anchor="middle" fill="#666" font-size="8" font-family="Segoe UI,sans-serif">Zielfortschritt</text><text x="70" y="142" text-anchor="middle" fill="#2c5f2e" font-size="8" font-family="Segoe UI,sans-serif">${done}/${total} Schritte</text><text x="140" y="75" fill="#1a3d1c" font-size="10" font-weight="bold" font-family="Segoe UI,sans-serif">Lernfelder – Standort</text>`;fieldColors.forEach((color,i)=>{const y=88+i*34;svgContent+=`<text x="140" y="${y}" fill="${color}" font-size="8.5" font-weight="bold" font-family="Segoe UI,sans-serif">${fieldNames[i]}</text><rect x="140" y="${y+4}" width="340" height="12" rx="6" fill="#e0d8c8"/><rect x="140" y="${y+4}" width="170" height="12" rx="6" fill="${color}"/>`;});const stepsToShow=zpData.steps.slice(0,4);svgContent+=`<text x="20" y="232" fill="#1a3d1c" font-size="10" font-weight="bold" font-family="Segoe UI,sans-serif">Nächste Schritte:</text>`;stepsToShow.forEach((s,i)=>{const y=248+i*16;svgContent+=`<text x="20" y="${y}" fill="${s.done?"#27ae60":"#666"}" font-size="8.5" font-family="Segoe UI,sans-serif">${s.done?"✅":"⏳"} ${i+1}. ${s.text.substring(0,55)}${s.text.length>55?"...":""}</text>`;});svgContent+=`<rect y="305" width="500" height="15" fill="#1a3d1c" rx="0"/><text x="250" y="318" text-anchor="middle" fill="rgba(255,255,255,0.7)" font-size="7.5" font-family="Segoe UI,sans-serif">Geistlich Denken Lernen · Ps 73,28 · Vertraulich</text>`;svg.innerHTML=svgContent;}
function renderZpStepChecks(){const c=document.getElementById("zp_step_checks");if(!c)return;if(!zpData.steps.length){c.innerHTML='<p style="font-size:.8rem;color:var(--text-light);">Noch keine Schritte vorhanden.</p>';return;}c.innerHTML=zpData.steps.map((s,i)=>`<div style="display:flex;align-items:center;gap:9px;padding:7px 0;border-bottom:1px solid #f0ebe0;"><input type="checkbox" id="zp_check_${i}" ${s.done?"checked":""} onchange="toggleZpStepDone(${i})" style="width:17px;height:17px;cursor:pointer;accent-color:var(--primary);"><label for="zp_check_${i}" style="font-size:.84rem;cursor:pointer;${s.done?"text-decoration:line-through;color:#999;":""}">${ZP_STEP_ICONS[s.type]} ${i+1}. ${s.text}${s.deadline?`<span style="font-size:.72rem;color:var(--accent);margin-left:5px;">📅 ${formatDate(s.deadline)}</span>`:""}</label></div>`).join("");}
function toggleZpStepDone(idx){zpData.steps[idx].done=!zpData.steps[idx].done;renderZpProgress();renderZpProgressSVG();renderZpStepChecks();renderZpTimeline();}
function collectZpData(){const g=id=>document.getElementById(id)?document.getElementById(id).value:"";zpData.mentee=g("zp_mentee");zpData.goalText=g("zp_goal_text");zpData.motivation=g("zp_motivation");zpData.successCriteria=g("zp_success_criteria");zpData.reformulated=g("zp_reformulated");zpData.bibleVerse=g("zp_bible_verse");zpData.lernfelder=[...zpSelectedLernfelder];zpData.lernfeldHelp=g("zp_lernfeld_help");zpData.finalDate=g("zp_final_date");zpData.milestones=zpMilestones;}
function saveZielplan(){collectZpData();const plan={...zpData,id:zpCurrentId||Date.now(),savedAt:new Date().toLocaleDateString("de-DE")};if(zpCurrentId){const idx=zpSavedPlans.findIndex(p=>p.id===zpCurrentId);if(idx>=0)zpSavedPlans[idx]=plan;else zpSavedPlans.unshift(plan);}else{zpCurrentId=plan.id;zpSavedPlans.unshift(plan);}localStorage.setItem("gdl_zielplaene",JSON.stringify(zpSavedPlans));const msg=document.getElementById("zp_saved_msg");if(msg){msg.classList.remove("hidden");setTimeout(()=>msg.classList.add("hidden"),3000);}renderZpSavedList();showToast("✅ Zielplan gespeichert!");}
function loadZielplan(id){const plan=zpSavedPlans.find(p=>p.id===id);if(!plan)return;zpCurrentId=id;zpData={...plan};zpSelectedLernfelder=plan.lernfelder||[];zpMilestones=plan.milestones||[];const fields={zp_mentee:plan.mentee,zp_goal_text:plan.goalText,zp_motivation:plan.motivation,zp_success_criteria:plan.successCriteria,zp_reformulated:plan.reformulated,zp_lernfeld_help:plan.lernfeldHelp,zp_final_date:plan.finalDate,zp_bible_verse:plan.bibleVerse};Object.entries(fields).forEach(([id,val])=>{const el=document.getElementById(id);if(el&&val)el.value=val;});if(plan.goalType)selectGoalType(plan.goalType);if(plan.goalKind)selectZpKind(plan.goalKind);zpSelectedLernfelder.forEach(f=>{const el=document.getElementById("zp_lf"+f);if(el){el.style.opacity="1";el.style.transform="scale(1.03)";}});renderZpStepsList();renderZpHelpers();renderSpiritualMilestones();updateZpTimelineSelect();zpGoToStep(1);}









function exportWirksamkeitPDF(){const today=new Date().toLocaleDateString("de-DE",{weekday:"long",year:"numeric",month:"long",day:"numeric"});const keys=["f1","f2","f3","f4","fruechte"];const labels=["Loslassen & aufgeben","Alles unter seine Herrschaft","Vertrauen in Gottes Macht","Aus der Fülle des Vaters","Früchte des Geistes"];const colors=["#8B2020","#2c5f2e","#1a4a7a","#6b3d8a","#27ae60"];let html=`<div style="font-family:'Segoe UI',sans-serif;color:#2a2a2a;max-width:180mm;"><div style="border-bottom:4px solid #2c5f2e;padding-bottom:12px;margin-bottom:16px;display:flex;justify-content:space-between;align-items:flex-end;"><div><h1 style="font-size:18pt;color:#1a3d1c;margin:0;">📊 Wirksamkeitsanalyse</h1><div style="font-size:9pt;color:#666;">Geistlich Denken Lernen – Verhaltensveränderung</div></div><div style="font-size:9pt;color:#666;">${today}</div></div><div style="font-size:9pt;font-style:italic;color:#666;margin-bottom:14px;">„Gott nahe zu sein ist mein Glück" – Psalm 73,28</div>`;keys.forEach((key,ki)=>{const items=WIRK_ITEMS[key];const vals=items.map((_,i)=>wirkData[key]&&wirkData[key][i]!==undefined?wirkData[key][i]:5);const avg=Math.round(vals.reduce((a,b)=>a+b,0)/vals.length);html+=`<div style="margin-bottom:14px;border-left:4px solid ${colors[ki]};padding:8px 12px;background:#fafaf5;border-radius:0 8px 8px 0;"><div style="font-weight:700;color:${colors[ki]};font-size:10pt;margin-bottom:6px;">${labels[ki]} – Ø ${avg}/10</div><div style="background:#e0d8c8;border-radius:4px;height:10px;margin-bottom:8px;overflow:hidden;"><div style="width:${avg*10}%;height:100%;background:${colors[ki]};border-radius:4px;"></div></div>${items.map((item,i)=>`<div style="display:flex;justify-content:space-between;font-size:8.5pt;padding:3px 0;border-bottom:1px solid #eee;"><span>${item.label}</span><strong style="color:${colors[ki]};">${vals[i]}/10</strong></div>`).join("")}</div>`;});html+=`<div style="margin-top:18px;padding-top:10px;border-top:1px solid #d4c9b0;font-size:7.5pt;color:#999;text-align:center;">Geistlich Denken Lernen · Wirksamkeitsanalyse · ${today} · Vertraulich</div></div>`;document.getElementById("pdfContent").innerHTML=html;setTimeout(()=>window.print(),400);}
function exportOrientierungPDF(){const today=new Date().toLocaleDateString("de-DE",{weekday:"long",year:"numeric",month:"long",day:"numeric"});const sections=[{key:"wichtig",label:"Was ist mir wichtig?"},{key:"lebe",label:"Was lebe ich schon?"},{key:"unwichtig",label:"Was ist mir unwichtig?"},{key:"hilfe",label:"Wo brauche ich Hilfe?"}];let html=`<div style="font-family:'Segoe UI',sans-serif;color:#2a2a2a;max-width:180mm;"><div style="border-bottom:4px solid #2c5f2e;padding-bottom:12px;margin-bottom:16px;display:flex;justify-content:space-between;align-items:flex-end;"><div><h1 style="font-size:18pt;color:#1a3d1c;margin:0;">🧭 Orientierung</h1><div style="font-size:9pt;color:#666;">Geistlich Denken Lernen – Standortbestimmung</div></div><div style="font-size:9pt;color:#666;">${today}</div></div><div style="font-size:9pt;font-style:italic;color:#666;margin-bottom:14px;">„Gott nahe zu sein ist mein Glück" – Psalm 73,28</div>`;sections.forEach(({key,label})=>{html+=`<div style="margin-bottom:14px;"><div style="font-size:10pt;font-weight:700;color:#1a3d1c;border-bottom:1px solid #d4c9b0;padding-bottom:4px;margin-bottom:8px;">${label}</div>`;ORIENT_QUESTIONS[key].forEach((q,i)=>{const ans=orientData[key]&&orientData[key][i];const icon=ans==="yes"?"✅":ans==="no"?"❌":ans==="help"?"🆘":"⬜";html+=`<div style="display:flex;gap:8px;padding:4px 0;font-size:9pt;border-bottom:1px solid #f0ebe0;"><span>${icon}</span><span>${q}</span></div>`;});html+="</div>";});html+=`<div style="margin-top:18px;padding-top:10px;border-top:1px solid #d4c9b0;font-size:7.5pt;color:#999;text-align:center;">Geistlich Denken Lernen · Orientierung · ${today} · Vertraulich</div></div>`;document.getElementById("pdfContent").innerHTML=html;setTimeout(()=>window.print(),400);}




const GDL_STORAGE_KEYS=["gdl_journal","gdl_mentees","gdl_mentors","gdl_orient","gdl_wirk","gdl_zielplaene","gdl_crosshair"];




function showToast(msg,duration=3500){const toast=document.getElementById("gdl_toast");if(!toast)return;toast.textContent=msg;toast.classList.remove("hidden");toast.style.opacity="1";clearTimeout(toast._timer);toast._timer=setTimeout(()=>{toast.style.opacity="0";setTimeout(()=>toast.classList.add("hidden"),300);},duration);}
document.addEventListener("DOMContentLoaded",()=>{renderBibleResults(BIBLE_LIBRARY);renderDailyImpulse();renderJournal();renderMentees();renderSavedMentors();initPWA();updateDataOverview();});
document.addEventListener("keydown",e=>{if(e.key==="Escape"){const modal=document.getElementById("crisisModal");if(modal&&modal.classList.contains("open"))closeCrisisModal();}});



// ===== DSGVO CONSENT & MENTEE =====
function updateConsentPreview() {
  const name = document.getElementById("menteeName") ? document.getElementById("menteeName").value.trim() : "";
  const preview = document.getElementById("consent_name_preview");
  if (preview) preview.textContent = name || "der/die Mentee";
}
function checkConsentReady() {
  const c1=document.getElementById("consent_check1"),c2=document.getElementById("consent_check2"),c3=document.getElementById("consent_check3");
  const btn=document.getElementById("addMenteeBtn");
  if(!btn)return;
  const ready=c1&&c2&&c3&&c1.checked&&c2.checked&&c3.checked;
  btn.disabled=!ready;btn.style.opacity=ready?"1":".5";btn.style.cursor=ready?"pointer":"not-allowed";
  btn.textContent=ready?"✅ Einwilligung bestätigt – Mentee anlegen":"🔒 Einwilligung bestätigen & Mentee anlegen";
}
function addMenteeWithConsent() {
  const c1=document.getElementById("consent_check1"),c2=document.getElementById("consent_check2"),c3=document.getElementById("consent_check3");
  if(!c1||!c2||!c3||!c1.checked||!c2.checked||!c3.checked){showToast("⚠️ Bitte alle Einwilligungen bestätigen.");return;}
  const name=g("menteeName");if(!name){showToast("⚠️ Bitte einen Namen eingeben.");return;}
  const mentee={
    id:Date.now(),name,
    nickname:g("menteeNickname"),phone:g("menteePhone"),mobile:g("menteeMobile"),
    email:g("menteeEmail"),street:g("menteeStreet"),city:g("menteeCity"),
    birthday:g("menteeBirthday"),note:g("menteeNote"),
    prayers:[],history:[],goals:[],
    createdAt:new Date().toLocaleDateString("de-DE"),
    consent:{given:true,date:g("consent_date"),form:g("consent_form"),timestamp:Date.now()}
  };
  mentees.push(mentee);
  localStorage.setItem("gdl_mentees",JSON.stringify(mentees));
  ["menteeName","menteeNickname","menteePhone","menteeMobile","menteeEmail","menteeStreet","menteeCity","menteeNote","consent_date"].forEach(id=>{const e=document.getElementById(id);if(e)e.value="";});
  const bd=document.getElementById("menteeBirthday");if(bd)bd.value="";
  ["consent_check1","consent_check2","consent_check3"].forEach(id=>{const e=document.getElementById(id);if(e)e.checked=false;});
  checkConsentReady();updateConsentPreview();renderMentees();showToast("✅ Mentee mit Einwilligung angelegt!");
}
function addMentee() { addMenteeWithConsent(); }

function renderMentees() {
  const c = document.getElementById("menteeList"); if (!c) return;
  if (!mentees.length) { c.innerHTML = '<div class="alert alert-info"><span>👤</span><span>Noch keine Mentees.</span></div>'; return; }
  c.innerHTML = mentees.map(m => {
    const initials = m.name.split(" ").map(w => w[0]).join("").substring(0,2).toUpperCase();
    const prayerCount = (m.prayers||[]).filter(p => p.status==="active").length;
    const goalCount = (m.goals||[]).filter(goal => !goal.done).length;
    return `<div class="mentee-card" onclick="openMenteeDetail(${m.id})">
      <div class="mentee-av">${initials}</div>
      <div class="mentee-info" style="flex:1;">
        <strong>${m.name}${m.nickname?` <span style="font-weight:400;color:var(--text-light);">(${m.nickname})</span>`:""}</strong>
        <div style="font-size:.76rem;color:var(--text-light);margin-top:2px;">${m.phone?"📞 "+m.phone+" · ":""}${m.email?"✉️ "+m.email:""}${m.city?"<br>🏠 "+m.city:""}</div>
        <div style="display:flex;gap:6px;margin-top:4px;">
          ${prayerCount>0?`<span class="badge badge-blue">🙏 ${prayerCount}</span>`:""}
          ${goalCount>0?`<span class="badge badge-green">🎯 ${goalCount}</span>`:""}
        </div>
      </div>
      <div style="display:flex;flex-direction:column;gap:5px;">
        ${m.phone?`<a href="tel:${m.phone}" class="btn btn-primary btn-sm" onclick="event.stopPropagation()">📞</a>`:""}
        ${m.email?`<a href="mailto:${m.email}" class="btn btn-outline btn-sm" onclick="event.stopPropagation()">✉️</a>`:""}
      </div>
    </div>`;
  }).join("");
}
function startMenteeSession(name) { showPage("session"); goToStep(1); const e=document.getElementById("menteePdfName"); if(e) e.value=name; }
function deleteMentee(id) { mentees=mentees.filter(m=>m.id!==id); localStorage.setItem("gdl_mentees",JSON.stringify(mentees)); renderMentees(); }
